version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      INTERVAL_SECONDS: 10
      CONFIG_PATH: /app/config.yml
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./config.yml:/app/config.yml
      - /app/node_modules
    command:
      - yarn
      - start
  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org.
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - 3001:3000
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/automatic.yml
    restart: always
